Deneme/urls.py
from django.conf.urls import url
from django.contrib import admin

from denemeTaslak import views

urlpatterns = [


    #url(r'^detail/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^question/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^add_question/$', views.QuestionView.as_view(), name='add_question'),
    url(r'^question/(?P<pk>[0-9]+)/add_choice/$', views.ChoiceView.as_view(), name='add_choice'),
    url(r'^question/(?P<pk>[0-9]+)/results/$', views.VoteView.as_view(), name='results'),
    url(r'^delete_choice/(?P<pk>[0-9]+)/$', views.DeleteChoice.as_view(), name='delete_choice'),
    url(r'^delete_question/(?P<pk>[0-9]+)/$', views.DeleteQuestion.as_view(), name='delete_question'),
]

denemeTaslak/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Question(models.Model):
    question_title = models.CharField(max_length=100)
    question_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __str__(self):
        return self.question_text

    def __str__(self):
        return self.question_title


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=300)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

denemeTaslak/forms.py
from django import forms
from denemeTaslak.models import Question
from denemeTaslak.models import Choice

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text',
                  'question_title']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice']

denemeTaslak/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from denemeTaslak.forms import QuestionForm
from denemeTaslak.forms import ChoiceForm
from denemeTaslak.models import Question
from denemeTaslak.models import Choice

from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'lastest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView, generic.View):
    model = Question
    template_name = 'detail.html'



    def post(self, request, pk):
        if request.POST.get('choice'):
            choice = Choice.objects.get(pk=request.POST.get('choice'))
            choice.vote += 1
            choice.save()
            return HttpResponseRedirect('/question/%s/results/' % self.kwargs.get('pk'))
        else:
            return HttpResponseRedirect('/question/%s/' % self.kwargs.get('pk'))

class QuestionView(generic.View):
    # model = QuestionForm
    def get(self, request):
        question_form = QuestionForm()
        return render(request, 'addQuestion.html', {
            'question_form': question_form
        })

    def post(self, request):

        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question_form.save()
            return HttpResponseRedirect(reverse('index'))

        else:

            return render(request, 'addQuestion.html', {
                'question_form': question_form,
                'errors': question_form.errors

            })

    template_name = "addQuestion.html"
    form_class = QuestionForm
    success_url = '/'


class ChoiceView(generic.View):
    def get(self, request, pk):
        choice_form = ChoiceForm()
        return render(request, 'add_choice.html', {
            'choice_form': choice_form
        })

    def post(self, request, pk):

        choice_form = ChoiceForm(request.POST)

        if choice_form.is_valid():
            Choice.objects.create(question_id=int(pk), choice=choice_form.data.get('choice'))

            return HttpResponseRedirect('/question/%s/' % self.kwargs.get('pk'))

        else:

            return render(request, 'add_choice.html', {
                'choice_form': choice_form,
                'errors': choice_form.errors

            })

    template_name = "add_choice.html"
    form_class = ChoiceForm
    success_url = '/'
    fields = 'question_id'


class DeleteChoice(generic.DeleteView):
    template_name = 'delete_choice.html'

    model = Choice

    def get(self, request,  *args, **kwargs):
        self.object = self.get_object()
        question_id = self.object.question_id
        self.object.delete()
        #Choice.objects.get(self.object.id).delete()
        return HttpResponseRedirect('/question/%s/' % question_id)

class DeleteQuestion(generic.DeleteView):
    template_name = 'delete_question.html'
    model = Question

    def get(self, request,  *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        #Choice.objects.get(self.object.id).delete()
        return HttpResponseRedirect(reverse('index'))


class VoteView(generic.DetailView):
    template_name = "results.html"
    model = Question

templates/addQuestion.html
{% extends 'master.html' %}
{% block content %}



<form action="" method="post">
    {% csrf_token %}
     <br>
{{ question_form }}
        <input type="submit" value="Save" />

</form>

{% endblock %}

templates/add_choice.html
{% extends 'master.html' %}

{% block content %}



<form action="" method="post">
    {% csrf_token %}
    <br>
{{ choice_form }}
        <input type="submit" value="Save" />

</form>

{% endblock %}

templates/detail.html
{% extends 'master.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<br><a href="{% url 'add_choice' question.id %}">Add Choice</a>
<head>
    <meta charset="UTF-8">
    <title>Question Details</title>
</head>
<body>

<br>
<br>
<h2>{{ question.question_text }}</h2>
</br>
{{ question.pub_date }}
</br>

<hr/>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {% for chc in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ chc.id }}" />
        <label for="choice{{ forloop.counter }}" >{{ chc.choice }} <a href="{% url 'delete_choice' chc.id %}"> Delete </a>  </label><br />
    {% endfor %}
<hr/>
    <input type="submit" value="Vote" />

</form>




</body>

</html>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<a href="{% url 'add_question' %}">Add Question</a>

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
{% if lastest_question_list %}
    <ul>
    {% for question in lastest_question_list %}
    <li><a href="{% url 'detail' question.pk %}">{{ question.question_title }}</a>  <a href="{% url 'delete_question' question.id %}"> Delete </a> </li>
    {% endfor %}
    </ul>
{% else %}

   <p>There are no questions available</p>
{% endif %}


</body>

</html>

templates/master.html
<a href="{% url 'index' %}">Home Page</a>

{% block content %}

{% endblock %}

templates/results.html
{% extends 'master.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>

    {% if question.choice_set %}
        {% for ch in question.choice_set.all %}

           <p>{{ ch.choice }} ----> {{ ch.vote }}</p>
        {% endfor %}

{% else %}
    <p>no votes</p>
{% endif %}

</body>
</html>
{% endblock %}